// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
    'aws_app_analytics': 'enable',
    'aws_cognito_identity_pool_id': 'us-east-1:f1e6626d-4006-4a5c-bb77-3eb8c5d34ad2',
    'aws_cognito_region': 'us-east-1',
    'aws_content_delivery': 'enable',
    'aws_content_delivery_bucket': 'amplifyauthexamples-hosting-mobilehub-1255542378',
    'aws_content_delivery_bucket_region': 'us-east-1',
    'aws_content_delivery_cloudfront': 'enable',
    'aws_content_delivery_cloudfront_domain': 'd11gn3hqh7usga.cloudfront.net',
    'aws_mobile_analytics_app_id': '4518c722dc7d452a821723907738a2ac',
    'aws_mobile_analytics_app_region': 'us-east-1',
    'aws_project_id': '47f13699-2fd5-11e8-ad8f-5d7d5cd6ce42',
    'aws_project_name': 'amplify-auth-examples-2018-03-24-21-35-58',
    'aws_project_region': 'us-east-1',
    'aws_resource_name_prefix': 'amplifyauthexamples-mobilehub-1255542378',
    'aws_sign_in_enabled': 'enable',
    'aws_user_pools': 'enable',
    'aws_user_pools_id': 'us-east-1_yVLXuG1Ew',
    'aws_user_pools_mfa_type': 'ON',
    'aws_user_pools_web_client_id': '5gobt8qq523qh5c3vbkrs6bqob',
}

export default awsmobile;
